<!-- Sydney Friedel and Shelby Coe -->
<!-- sfriede5 and scoe4 -->

<head><title>Entity 2</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';

		   echo "<h2>Effects of Education Quality on Health Factors Later in Life</h2>";

		   //prepare statements and call queries
			if ($stmt1 = $conn->prepare("CALL Query9High()")) {

      			   //Run the actual query
      			   if ($stmt1->execute()) {

         		      //Store result set generated by the prepared statement
         		      $result1 = $stmt1->get_result();
			      
			      $result1Worked = 0;
			      
         		      if (($result1) && ($result1->num_rows != 0)) {

			      $result1Worked = 1;
			      
			      echo "<h3> For states in which the rate of drug overdoses or sucide are significantly higher or lower than other states, what was the highschool graduation rate? Average SAT/ACT scores?</h3>";
			      echo "<h4> Here, we defined 'significantly lower or higher' as states where the suicide rate or number of drug overdoses (in 1000s) were greater than or equal to 1.5 standard deviations above or below the mean value of that statistic across all 50 states</h4>";

			      echo "<h5> Statistics for states with siginificantly high suicide rates or number of drug overdoses </h5>";
            		      //Create table to display results
           		      echo "<table border=\"1px solid black\">";
            		      echo "<tr><th> State </th> <th> Highschool Graduation Rate </th><th> Average SAT Score </th><th> Average ACT Score</th></tr>";

            		       //Report result set by visiting each row in it
            		       while ($row1 = $result1->fetch_row()) {
               		       	     echo "<tr>";
               			     echo "<td>".$row1[0]."</td>";
               			     echo "<td>".$row1[1]."</td>";
				     echo "<td>".$row1[2]."</td>";
				     echo "<td>".$row1[3]."</td>";

               			     echo "</tr>";
            			     }

            			     echo "</table>";
				 //result 1 was empty
				     	  
         			} else {

				  if(!($result1)) {
				  	echo "Internal error: procedure failed";
				  }
				}
				  
                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }
				
			   	// close down prepared statement
      			      	$stmt1->close();
			} else {
		           //Call to execute failed, e.g. because server is no longer reachable,
         	      	   //or because supplied values are of the wrong type
         	      	   echo "Execute failed.<br>";
			}
		} else {
       		  //A problem occurred when preparing the statement; check for syntax errors
       		  //and misspelled attribute names in the statement string.
      		  echo "Prepare failed.<br>";
      		  $error = $conn->errno . ' ' . $conn->error;
      		  echo $error;
		 }
		  
		  //call next query
	           // call low query 9 if the high query 9 succeeded
		   if ($result1Worked == 1) {
                   if ($stmtlow = $conn->prepare("CALL Query9Low()")) {

                       //Run the actual query
                       if ($stmtlow->execute()) {

                           //Store result set generated by the prepared statement
                           $resultlow = $stmtlow->get_result();

                           if (($resultlow) && ($resultlow->num_rows != 0)) {
                               echo "<h5> Statistics for states with significantly low suicide rates or number of drug overdoses </h5>";						//Create table to display results
                             echo "<table border=\"1px solid black\">";
                             echo "<tr><th> State </th> <th> Highschool Graduation Rate </th><th> Average SAT Score </th><th> Average ACT Score</th></tr>";
                             //Report result set by visiting each row in it
                             while ($rowl = $resultlow->fetch_row()) {
                                      echo "<tr>";
				      echo "<td>".$rowl[0]."</td>";
                                      echo "<td>".$rowl[1]."</td>";
                                      echo "<td>".$rowl[2]."</td>";
                                      echo "<td>".$rowl[3]."</td>";
                                      echo "</tr>";
                              }
                              echo "</table>";

                                     } else {

                                        if(!($resultlow)) {
                                         echo "Internal error: procedure failed";
					 }
				     }
				     
                                  if(($resultlow)) {
                                        //We are done with the result set returned above, so free it
                                        $resultlow->free_result();
                                  }

                                  // close down prepared statement
                                  $stmtlow->close();

                                  } else {
                                    //Call to execute failed, e.g. because server is no longer reachable,
                                    //or because supplied values are of the wrong type
                                    echo "Execute failed.<br>";
                                    }
                                 } else {
                                   //A problem occurred when preparing the statement; check for syntax errors
                                   //and misspelled attribute names in the statement string.
                                   echo "Prepare failed.<br>";
                                   $error = $conn->errno . ' ' . $conn->error;
                                   echo $error;
                                 }
			}
	             //call next query
		     if ($stmt2 = $conn->prepare("CALL Query13()")) {

                           //Run the actual query
                           if ($stmt2->execute()) {

                              //Store result set generated by the prepared statement
                              $result2 = $stmt2->get_result();

                              if (($result2) && ($result2->num_rows != 0)) {
			         //construct an array in which we'll store our data
                                 $dataPointsSuicide = array();
                                 $dataPointsHom = array();
                                 $dataPointsDrugs= array();

                               while ($row2 = $result2->fetch_row()) {
			             array_push($dataPointsSuicide, array("y"=> $row2[2], "x"=> $row2[4], "label"=>$row2[0]));
                                     array_push($dataPointsHom, array("y"=> $row2[1], "x"=> $row2[4], "label"=>$row2[0]));
                                     array_push($dataPointsDrugs, array("y"=> $row2[3], "x"=> $row2[4], "label"=>$row2[0]));
                                     }

                                   
                                } else {

                                  if(!($result2)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result2)) {
                                        //We are done with the result set returned above, so free it
                                        $result2->free_result();
                                  }

                                // close down prepared statement
                                $stmt2->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

                           if ($stmt3 = $conn->prepare("CALL Query15()")) {

                           //Run the actual query
                           if ($stmt3->execute()) {

                              //Store result set generated by the prepared statement
                              $result3 = $stmt3->get_result();

                              if (($result3) && ($result3->num_rows != 0)) {

                              echo "<h3>  Of states with the highest rates of suicide, what is their average annual education funding and teacher starting salary? How does this compare to states with the lowest rates of suicide?</h3>";

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> State </th> <th> Education Spending Per Pupil</th><th> Average Teacher Starting Salary</th><th> Suicide Rate </th></tr>";
                               //Report result set by visiting each row in it
                               while ($row3 = $result3->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row3[0]."</td>";
                                     echo "<td>".$row3[1]."</td>";
                                     echo "<td>".$row3[2]."</td>";
				     echo "<td>".$row3[3]."</td>";

                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {

                                  if(!($result3)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result3)) {
                                        //We are done with the result set returned above, so free it
                                        $result3->free_result();
                                  }

                                // close down prepared statement
                                $stmt3->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

                      
   // close the connection opened by open.php
   $conn->close();
?>
</body>


<html>
<head>
<script type="text/javascript">
window.onload = function () {
       var chart = new CanvasJS.Chart("container1", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "light1", // "light1", "light2", "dark1", "dark2"
                title:{
                        text: "Suicide Rate as a Function of Education Performance",
                        fontFamily: "verdana",
                        fontWeight: "bold",
                        fontSize: 18,
                },
                data: [{
                        type: "line", //change type to column, bar, line, area, pie, etc
                        dataPoints: <?php echo json_encode($dataPointsSuicide, JSON_NUMERIC_CHECK); ?>,
                }],
                axisX:{
                        title:"Cummulative NAEP Score",
                                labelFormatter: function ( e ) {
                                return e.value;
                        },
                        interval: 10
                 },
                 axisY:{
                        title:"Suicide Rate",
                 }


        });
        chart.render();
	
         var chart = new CanvasJS.Chart("container2", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "light1", // "light1", "light2", "dark1", "dark2"
                title:{
                        text: "Homicide Rate as a Function of Educational Performance",
                        fontFamily: "verdana",
                        fontWeight: "bold",
                        fontSize: 18,
                },
                data: [{
                        type: "line", //change type to column, bar, line, area, pie, etc
                        dataPoints: <?php echo json_encode($dataPointsHom, JSON_NUMERIC_CHECK); ?>
                }],
                axisX:{
                                title:"Cummulative NAEP Score",
                                labelFormatter: function ( e ) {
                                return e.value;
                        },
                        interval: 10

                 },
                 axisY:{
                        title:"Homicide Rate",
                 }

        });
        chart.render();

         var chart = new CanvasJS.Chart("container3", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "light1", // "light1", "light2", "dark1", "dark2"
                title:{
                        text: "Number of Drug Overdoses as a Function of Educational Performance",
                        fontFamily: "verdana",
                        fontWeight: "bold",
                        fontSize: 18,
                },
                data: [{
                        type: "line", //change type to column, bar, line, area, pie, etc
                        dataPoints: <?php echo json_encode($dataPointsDrugs, JSON_NUMERIC_CHECK); ?>
                }],
                axisX:{
                                title:"Cummulative NAEP Score",
                                labelFormatter: function ( e ) {
                                return e.value;
                        },
                        interval: 10

                 },
                 axisY:{
                        title:"Number of Drug Overdoses (in 1000s)",
                 }

        });
        chart.render();
	
}
</script>
</head>
<body>
        <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        
        <h3 style = "font-family: 'verdana'">  In order of best to worst-scored public education system (in terms of NAEP scores), here is the suicide rate, homicide rate, and number of drug overdoses for each state (for which educational and health data was available.) </h3>
	<h5 style = "font-family: 'verdana'"> Cummulative NAEP Score = NAEP Reading + NAEP Math </h5>
        <div id="container1" style="height: 300px; width: 100%;display: inline-block;"></div>
        <div id="container2" style="height: 300px; width: 100%;display: inline-block;"></div>
        <div id="container3" style="height: 300px; width: 100%;display: inline-block;"></div>
     <style>
	body {font-family: 'verdana';}
     </style>
</body>
</html>
