<!-- Sydney Friedel and Shelby Coe -->
<!-- sfriede5 and scoe4 -->

<head><title>Query 6</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';

	//get user input and perform error-checking on it
	$q6state = $_POST['q6state'];


	if(!empty($q6state)) {
		$q6state = trim($q6state);
		if (strcmp($q6state, 'Alabama') == 0 || strcmp($q6state, 'Alaska') == 0 || strcmp($q6state, 'Arizona') == 0
		|| strcmp($q6state, 'Arkansas') == 0 || strcmp($q6state, 'California') == 0 || strcmp($q6state, 'Colorado') == 0
		|| strcmp($q6state, 'Connecticut') == 0 || strcmp($q6state, 'Delaware') == 0 || strcmp($q6state, 'Flordia') == 0
		|| strcmp($q6state, 'Georgia') == 0 || strcmp($q6state, 'Hawaii') == 0 || strcmp($q6state, 'Idaho') == 0
		|| strcmp($q6state, 'Illinois') == 0 || strcmp($q6state, 'Indiana') == 0 || strcmp($q6state, 'Iowa') == 0
		|| strcmp($q6state, 'Kansas') == 0 || strcmp($q6state, 'Kentucky') == 0 || strcmp($q6state, 'Louisiana') == 0
		|| strcmp($q6state, 'Maine') == 0 || strcmp($q6state, 'Maryland') == 0 || strcmp($q6state, 'Massachusetts') == 0
		|| strcmp($q6state, 'Michigan') == 0 || strcmp($q6state, 'Minnesota') == 0 || strcmp($q6state, 'Mississippi') == 0
		|| strcmp($q6state, 'Missouri') == 0 || strcmp($q6state, 'Montana') == 0 || strcmp($q6state, 'Nebraska') == 0
		|| strcmp($q6state, 'Nevada') == 0 || strcmp($q6state, 'New Hampshire') == 0 || strcmp($q6state, 'New Jersey') == 0
		|| strcmp($q6state, 'New Mexico') == 0 || strcmp($q6state, 'New York') == 0 || strcmp($q6state, 'North Carolina') == 0
		|| strcmp($q6state, 'North Dakota') == 0 || strcmp($q6state, 'Ohio') == 0 || strcmp($q6state, 'Oklahoma') == 0
		|| strcmp($q6state, 'Oregon') == 0 || strcmp($q6state, 'Pennsylvania') == 0 || strcmp($q6state, 'Rhode Island') == 0
		|| strcmp($q6state, 'South Carolina') == 0 || strcmp($q6state, 'South Dakota') == 0 || strcmp($q6state, 'Tennessee') == 0
		|| strcmp($q6state, 'Texas') == 0 || strcmp($q6state, 'Utah') == 0 || strcmp($q6state, 'Vermont') == 0
		|| strcmp($q6state, 'Virginia') == 0 || strcmp($q6state, 'Washington') == 0 || strcmp($q6state, 'West Virginia') == 0
		|| strcmp($q6state, 'Wisconsin') == 0 || strcmp($q6state, 'Wyoming') == 0 || strcmp($q6state, 'Washington DC') == 0
		|| strcmp($q6state, 'Puerto Rico') == 0 || strcmp($q6state, 'Washington D.C.') == 0 || strcmp($q6state, 'Guam') == 0
		||  strcmp($q6state, 'US Virgin Islands') == 0 ||  strcmp($q6state, 'Northern Mariana Islands') == 0
		|| strcmp($q6state, 'American Samoa') == 0 ||  strcmp($q6state, 'Midway Atoll') == 0 ||  strcmp($q6state, 'Palmyra Atoll') == 0
		||  strcmp($q6state, 'Baker Island') == 0 ||  strcmp($q6state, 'Howland Island') == 0 ||  strcmp($q6state, 'Jarvis Island') == 0
		||  strcmp($q6state, 'Johnston Atoll') == 0 ||  strcmp($q6state, 'Kingman Reef') == 0 ||  strcmp($q6state, 'Wake Island') == 0
		||  strcmp($q6state, 'Navassa Island') == 0) {
		
   		   //input is within range, so we can make stored procedure calls safely
		   echo "<h2>What is the difference between the US born and foreign born median incomes for $q6state, and how racially diverse is this state? How does this compare to states with the minimum and maximum median incomes?</h2><br>";

		   //call stored procedures defined on dbase

		   if ($stmt1 = $conn->prepare("CALL Query6(?)")) {
      			   $stmt1->bind_param("s", $q6state);

      			   //Run the actual query
      			   if ($stmt1->execute()) {

         		      //Store result set generated by the prepared statement
         		      $result1 = $stmt1->get_result();

         		      if (($result1) && ($result1->num_rows != 0)) {
                               $dataPointsMax = array();
			       $dataPointsMin = array();
                               $dataPointsState = array();

			       $row1 = $result1->fetch_row();
			       array_push($dataPointsMax, array( "y"=> $row1[2], "label"=> "white"));
			       array_push($dataPointsMax, array( "y"=> $row1[3], "label"=> "black"));
                               array_push($dataPointsMax, array( "y"=> $row1[4], "label"=> "asian"));
                               array_push($dataPointsMax, array( "y"=> $row1[5], "label"=> "indigenous"));
                               array_push($dataPointsMax, array( "y"=> $row1[6], "label"=> "other"));
                               $maxForeignBorn = $row1[0];
			       $maxUSBorn = $row1[1];
			       $maxHisp = $row1[7];
			       $maxNonHisp = $row1[8];


                               $row2 = $result1->fetch_row();
                               array_push($dataPointsMin, array( "y"=> $row2[2], "label"=> "white"));
                               array_push($dataPointsMin, array( "y"=> $row2[3], "label"=> "black"));
                               array_push($dataPointsMin, array( "y"=> $row2[4], "label"=> "asian"));
                               array_push($dataPointsMin, array( "y"=> $row2[5], "label"=> "indigenous"));
                               array_push($dataPointsMin, array( "y"=> $row2[6], "label"=> "other"));
                               $minForeignBorn = $row2[0];
                               $minUSBorn = $row2[1];
                               $minHisp = $row2[7];
                               $minNonHisp = $row2[8];



                               $row3 = $result1->fetch_row();
                               array_push($dataPointsState, array( "y"=> $row3[2], "label"=> "white"));
                               array_push($dataPointsState, array( "y"=> $row3[3], "label"=> "black"));
                               array_push($dataPointsState, array( "y"=> $row3[4], "label"=> "asian"));
                               array_push($dataPointsState, array( "y"=> $row3[5], "label"=> "indigenous"));
                               array_push($dataPointsState, array( "y"=> $row3[6], "label"=> "other"));
                               $stateForeignBorn = $row3[0];
                               $stateUSBorn = $row3[1];
                               $stateHisp = $row3[7];
                               $stateNonHisp = $row3[8];


                               
            		      //Create table to display results
           		       echo "<table border=\"1px solid black\">";
            		       echo "<tr><th>Entity</th><th> ForeignBornIncome </th> <th> USBornIncome </th><th> % Hispanic or Latino </th> <th> % Not Hispanic or Latino </th></tr>";
			       echo"<tr><td>Maximum Income States</td><td>".$maxForeignBorn."</td><td>".$maxUSBorn."</td><td>".$maxHisp."</td><td>".$maxNonHisp."</td></tr>";
                               echo"<tr><td>Minimum Income States</td><td>".$minForeignBorn."</td><td>".$minUSBorn."</td><td>".$minHisp."</td><td>".$minNonHisp."</td></tr>";
                               echo"<tr><td>".$q6state."</td><td>".$stateForeignBorn."</td><td>".$stateUSBorn."</td><td>".$stateHisp."</td><td>".$stateNonHisp."</td></tr>";

            		       echo "</table>";

         			} else {

				  if(!($result1)) {
				  	echo "We do not have information available for this state. Remember that the input must be a valid, capitalized state or US territory name.";
				  }
				}
				  
                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }
				
			   	// close down prepared statement
      			      	$stmt1->close();
			} else {
		           //Call to execute failed, e.g. because server is no longer reachable,
         	      	   //or because supplied values are of the wrong type
         	      	   echo "Execute failed.<br>";
			}
		} else {
       		  //A problem occurred when preparing the statement; check for syntax errors
       		  //and misspelled attribute names in the statement string.
      		  echo "Prepare failed.<br>";
      		  $error = $conn->errno . ' ' . $conn->error;
      		  echo $error;
             	}
	   } else {
	   
	     echo "Invalid input given. Remember that the input must be a valid, capitalized state or US territory name";
	   }
	} else {
	  echo "State Name Not Set";
	}
      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

<html>
<head>
<script type="text/javascript">
window.onload = function () {

        var chart = new CanvasJS.Chart("container1", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "light1", // "light1", "light2", "dark1", "dark2"
                title:{
                        text: "Average Racial Diversity Statistics For States with Maximum Median Income",
                        fontFamily: "verdana",
                        fontWeight: "bold"
                },
                data: [{
		        type: "pie",
		        startAngle: 240,
			yValueFormatString: "##0.00\"%\"",
		        indexLabel: "{label} {y}",
                        dataPoints: <?php echo json_encode($dataPointsMax, JSON_NUMERIC_CHECK); ?>
                }],
        });
        chart.render();
	        var chart = new CanvasJS.Chart("container2", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "light1", // "light1", "light2", "dark1", "dark2"
                title:{
                        text: "Average Racial Diversity Statistics For States with Minimum Median Income",
                        fontFamily: "verdana",
                        fontWeight: "bold"
                },
                data: [{
                        type: "pie",
                        startAngle: 240,
                        yValueFormatString: "##0.00\"%\"",
                        indexLabel: "{label} {y}",
                        dataPoints: <?php echo json_encode($dataPointsMin, JSON_NUMERIC_CHECK); ?>
                }],
        });
        chart.render();
        var chart = new CanvasJS.Chart("container3", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "light1", // "light1", "light2", "dark1", "dark2"
                title:{
                        text: "Average Racial Diversity Statistics For The Given State",
                        fontFamily: "verdana",
                        fontWeight: "bold"
                },
                data: [{
                        type: "pie",
                        startAngle: 240,
                        yValueFormatString: "##0.00\"%\"",
                        indexLabel: "{label} {y}",
                        dataPoints: <?php echo json_encode($dataPointsState, JSON_NUMERIC_CHECK); ?>
                }],
        });
        chart.render();

}
</script>
</head>
<body>
        <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
	<br>
        <div id="container3" style="height: 300px; width: 100%;display: inline-block;"></div>
        <div id="container1" style="height: 300px; width: 100%;display: inline-block;"></div>
        <div id="container2" style="height: 300px; width: 100%;display: inline-block;"></div>

     <style>
        body {font-family: 'verdana'; font-size: 18px;}
     </style>

</body>
</html>
