<head><title>Query 6</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';


	//Override the PHP configuration file to display all errors
	//This is useful during development but generally disabled before release
	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);


		   echo "<h2>Effects of Education Quality on Financial Factors Later in Life </h2>";

		   //prepare statements and call queries
			if ($stmt1 = $conn->prepare("CALL Query1()")) {

      			   //Run the actual query
      			   if ($stmt1->execute()) {

         		      //Store result set generated by the prepared statement
         		      $result1 = $stmt1->get_result();

         		      if (($result1) && ($result1->num_rows != 0)) {

			      echo "<h3>  In order of best to worst-scored public education system (in terms of NAEP and standardized test scores), here is the unemployment rate, percent of population that is homeless, and the average starting salary of teachers for each state. </h3>"; 


            		      //Create table to display results
           		       echo "<table border=\"1px solid black\">";
            		       echo "<tr><th> State </th> <th> Education Performance Score </th><th> Average Teacher Starting Salary</th> <th> Unemployment Rate </th> <th> Percent of Population That's Homeless </th></tr>";

            		       //Report result set by visiting each row in it
            		       while ($row1 = $result1->fetch_row()) {
               		       	     echo "<tr>";
               			     echo "<td>".$row1[1]."</td>";
               			     echo "<td>".$row1[0]."</td>";
				     echo "<td>".$row1[2]."</td>";
				     echo "<td>".$row1[3]."</td>";
				     echo "<td>".$row1[4]."</td>";

               			     echo "</tr>";
            			     }

            			     echo "</table>";

         			} else {

				  if(!($result1)) {
				  	echo "Internal error: procedure failed";
				  }
				}
				  
                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }
				
			   	// close down prepared statement
      			      	$stmt1->close();
			} else {
		           //Call to execute failed, e.g. because server is no longer reachable,
         	      	   //or because supplied values are of the wrong type
         	      	   echo "Execute failed.<br>";
			}
		} else {
       		  //A problem occurred when preparing the statement; check for syntax errors
       		  //and misspelled attribute names in the statement string.
      		  echo "Prepare failed.<br>";
      		  $error = $conn->errno . ' ' . $conn->error;
      		  echo $error;
             	}
		     if ($stmt2 = $conn->prepare("CALL Query4Highschool()")) {

                           //Run the actual query
                           if ($stmt2->execute()) {

                              //Store result set generated by the prepared statement
                              $result2 = $stmt2->get_result();

                              if (($result2) && ($result2->num_rows != 0)) {

                              echo "<h3>  See the average income for adults in the five states with the highest high school graduation rate and lowest high school graduation rate</h3>";

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> State </th> <th> Highschool Graduation Rate</th><th> Median Income</th></tr>";
                               //Report result set by visiting each row in it
                               while ($row2 = $result2->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row2[0]."</td>";
                                     echo "<td>".$row2[2]."</td>";
                                     echo "<td>".$row2[1]."</td>";

                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {

                                  if(!($result2)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result2)) {
                                        //We are done with the result set returned above, so free it
                                        $result2->free_result();
                                  }

                                // close down prepared statement
                                $stmt2->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

                           if ($stmt3 = $conn->prepare("CALL Query4College()")) {

                           //Run the actual query
                           if ($stmt3->execute()) {

                              //Store result set generated by the prepared statement
                              $result3 = $stmt3->get_result();

                              if (($result3) && ($result3->num_rows != 0)) {

                              echo "<h3>  See how this changes if we use percent of adults completing college instead</h3>";

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> State </th> <th> Percent Completing College</th><th> Median Income</th></tr>";
                               //Report result set by visiting each row in it
                               while ($row3 = $result3->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row3[0]."</td>";
                                     echo "<td>".$row3[2]."</td>";
                                     echo "<td>".$row3[1]."</td>";

                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {

                                  if(!($result3)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result3)) {
                                        //We are done with the result set returned above, so free it
                                        $result3->free_result();
                                  }

                                // close down prepared statement
                                $stmt3->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

                      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

