<head><title>Query 6</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';


	//Override the PHP configuration file to display all errors
	//This is useful during development but generally disabled before release
	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);


		   echo "<h2>Effects of Education Quality on Health Factors Later in Life</h2>";

		   //prepare statements and call queries
			if ($stmt1 = $conn->prepare("CALL Query9()")) {

      			   //Run the actual query
      			   if ($stmt1->execute()) {

         		      //Store result set generated by the prepared statement
         		      $result1 = $stmt1->get_result();

         		      if (($result1) && ($result1->num_rows != 0)) {

			      echo "<h3> For states in which the rate of drug overdoses or sucide are significantly lower than other states, what was the highschool graduation rate? Average SAT/ACT scores?</h3>"; 


            		      //Create table to display results
           		       echo "<table border=\"1px solid black\">";
            		       echo "<tr><th> State </th> <th> Highschool Graduation Rate </th><th> Average SAT Score </th><th> Average ACT Score</th></tr>";

            		       //Report result set by visiting each row in it
            		       while ($row1 = $result1->fetch_row()) {
               		       	     echo "<tr>";
               			     echo "<td>".$row1[1]."</td>";
               			     echo "<td>".$row1[0]."</td>";
				     echo "<td>".$row1[2]."</td>";
				     echo "<td>".$row1[3]."</td>";

               			     echo "</tr>";
            			     }

            			     echo "</table>";

         			} else {

				  if(!($result1)) {
				  	echo "Internal error: procedure failed";
				  }
				}
				  
                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }
				
			   	// close down prepared statement
      			      	$stmt1->close();
			} else {
		           //Call to execute failed, e.g. because server is no longer reachable,
         	      	   //or because supplied values are of the wrong type
         	      	   echo "Execute failed.<br>";
			}
		} else {
       		  //A problem occurred when preparing the statement; check for syntax errors
       		  //and misspelled attribute names in the statement string.
      		  echo "Prepare failed.<br>";
      		  $error = $conn->errno . ' ' . $conn->error;
      		  echo $error;
             	}
		     if ($stmt2 = $conn->prepare("CALL Query13()")) {

                           //Run the actual query
                           if ($stmt2->execute()) {

                              //Store result set generated by the prepared statement
                              $result2 = $stmt2->get_result();

                              if (($result2) && ($result2->num_rows != 0)) {

                              echo "<h3> For states with the best and worst public school systems, how do the number of homicides, suicides, and drug overdose statistics compare?</h3>";

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> State </th> <th> Suicide Rate</th><th> Homicide Rate</th> <th> Number of Drug Overdoses </th></tr>";
                               //Report result set by visiting each row in it
                               while ($row2 = $result2->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row2[0]."</td>";
                                     echo "<td>".$row2[2]."</td>";
                                     echo "<td>".$row2[1]."</td>";
				     echo "<td>".$row2[3]."</td>";
                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {

                                  if(!($result2)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result2)) {
                                        //We are done with the result set returned above, so free it
                                        $result2->free_result();
                                  }

                                // close down prepared statement
                                $stmt2->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

                           if ($stmt3 = $conn->prepare("CALL Query15()")) {

                           //Run the actual query
                           if ($stmt3->execute()) {

                              //Store result set generated by the prepared statement
                              $result3 = $stmt3->get_result();

                              if (($result3) && ($result3->num_rows != 0)) {

                              echo "<h3>  Of states with the highest rates of suicide, what is their average annual education funding and teacher starting salary? How does this compare to states with the lowest rates of suicide?</h3>";

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> State </th> <th> Education Spending Per Pupil</th><th> Average Teacher Starting Salary</th><th> Suicide Rate </th></tr>";
                               //Report result set by visiting each row in it
                               while ($row3 = $result3->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row3[0]."</td>";
                                     echo "<td>".$row3[1]."</td>";
                                     echo "<td>".$row3[2]."</td>";
				     echo "<td>".$row3[3]."</td>";

                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {

                                  if(!($result3)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result3)) {
                                        //We are done with the result set returned above, so free it
                                        $result3->free_result();
                                  }

                                // close down prepared statement
                                $stmt3->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

                      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

