<!-- Sydney Friedel and Shelby Coe -->
<!-- sfriede5 and scoe4 -->

<head><title>Insert Risk Factors</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';


	//Override the PHP configuration file to display all errors
	//This is useful during development but generally disabled before release
	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);

	//get user input and perform error-checking on it
	$state = $_POST['rfState'];
	$population = $_POST['rfPop'];
	$cancer = $_POST['cancer'];
        $obesity = $_POST['obesity'];
        $sti = $_POST['sti'];
        
	$success = 0;
	
	if(!empty($state) && isset($population) && isset($cancer) && isset($obesity) && isset($sti)) {

			   if ($stmt1 = $conn->prepare("CALL InsertRiskFactors(?, ?, ?, ?, ?)")) {
                           $stmt1->bind_param("siddi", $state, $population, $cancer, $obesity, $sti);

                           //Run the actual query
                           if ($stmt1->execute()) {

                              //Store result set generated by the prepared statement
                              $result1 = $stmt1->get_result();
			      
			      //if there were no errors, the result should be empty. if a primary key or integrity constraint error
			      // occurred, it will be contained in the result
                              if (($result1) && ($result1->num_rows != 0)) {

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> Error: Insertion Unsuccessful </th></tr>";

                               //Report result set by visiting each row in it
                               while ($row1 = $result1->fetch_row()) {
                                    echo "<tr>";
                                        echo "<td>".$row1[0]."</td>";
                                        echo "</tr>";
                                    }

                                     echo "</table>";

                                } else {

				  echo "Your record was successfully inserted into the Risk Factors table! See it in the table below";

				  $success = 1;
				}

			       if(($result1)) {
                                    //We are done with the result set returned above, so free it
                               	    $result1->free_result();    
			       }
                                // close down prepared statement
                                $stmt1->close();
				
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Unable to insert record into the Risk Factors table because the supplied values were of the wrong type or out of range. Please ensure all inputs match their given descriptions.<br>";

                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }


	} else {

	  echo "Please ensure all parameters are set";
	}

	if($success == 1) {

		    if ($stmt2 = $conn->prepare("SELECT * FROM RiskFactors")) {
		    
		           //Run the actual query
                           if ($stmt2->execute()) {

                              //Store result set generated by the prepared statement
                              $result2 = $stmt2->get_result();
                             
                              
                              if (($result2) && ($result2->num_rows != 0)) {

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
			       echo "<tr><th>State</th><th>Cancer Mortality Per 100,000 People</th><th>STIs Per 100,000</th><th>Obesity Prevalence</th></tr>";

                               //Report result set by visiting each row in it
                               while ($row2 = $result2->fetch_row()) {
                                    echo "<tr>";
                                        echo "<td>".$row2[0]."</td>";
				        echo "<td>".$row2[1]."</td>";
                                        echo "<td>".$row2[2]."</td>";
                                        echo "<td>".$row2[3]."</td>";
                        
                                        echo "</tr>";
                                    }

                                     echo "</table>";

                                }

		               if(($result2)) {
                               //We are done with the result set returned above, so free it
                                    $result2->free_result();
                               }
                                // close down prepared statement
                                $stmt2->close();

                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }

		     } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

	}
      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

<html>
<body>
     <style>
        body {font-family: 'verdana'; font-size: 18px;}
     </style>

</body>
</html>
