<!-- Sydney Friedel and Shelby Coe -->
<!-- sfriede5 and scoe4 -->

<head><title>Insert Education</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';


	//Override the PHP configuration file to display all errors
	//This is useful during development but generally disabled before release
	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);

	//get user input and perform error-checking on it
	$state = $_POST['eduState'];
	$population = $_POST['eduPop'];
	$SAT = $_POST['SAT'];
        $ACT = $_POST['ACT'];
        $NAEPRead = $_POST['NAEPRead'];
        $NAEPMath = $_POST['NAEPMath'];
        $eduSpending = $_POST['eduSpending'];
        $percentCollege = $_POST['percentCollege'];
        $hsGradRate = $_POST['hsGradRate'];
	$teacherSal = $_POST['teacherSal'];
	
	$success = 0;
	
	if(isset($state) && isset($population) && isset($SAT) && isset($ACT) && isset($NAEPRead) && isset($NAEPMath) && isset($eduSpending) && isset($hsGradRate) &&  isset($percentCollege) && isset($teacherSal)) {

			   if ($stmt1 = $conn->prepare("CALL InsertEducation(?,?, ?, ?, ?, ?, ?, ?, ?, ?)")) {
                           $stmt1->bind_param("siiidiiddd", $state, $population, $teacherSal, $SAT, $ACT, $NAEPRead, $NAEPMath, $hsGradRate, %percentCollege, $eduSpending);

                           //Run the actual query
                           if ($stmt1->execute()) {

                              //Store result set generated by the prepared statement
                              $result1 = $stmt1->get_result();
			      
			      //if there were no errors, the result should be empty. if a primary key or integrity constraint error
			      // occurred, it will be contained in the result
                              if (($result1) && ($result1->num_rows != 0)) {

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> Error: Insertion Unsuccessful </th></tr>";

                               //Report result set by visiting each row in it
                               while ($row1 = $result1->fetch_row()) {
                                    echo "<tr>";
                                        echo "<td>".$row1[0]."</td>";
                                        echo "</tr>";
                                    }

                                     echo "</table>";

                                } else {

				  echo "Your record was successfully inserted into the Education table! See it in the table below";

				  $success = 1;
				}

			       if(($result1)) {
                                    //We are done with the result set returned above, so free it
                               	    $result1->free_result();    
			       }
                                // close down prepared statement
                                $stmt1->close();
				
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }


	} else {

	  echo "Please ensure all parameters are set";
	}

	if($success == 1) {

		    if ($stmt2 = $conn->prepare("SELECT * FROM Education")) {
		    
		           //Run the actual query
                           if ($stmt2->execute()) {

                              //Store result set generated by the prepared statement
                              $result2 = $stmt2->get_result();
                             
                              
                              if (($result2) && ($result2->num_rows != 0)) {

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";

                               //Report result set by visiting each row in it
                               while ($row2 = $result2->fetch_row()) {
                                    echo "<tr>";
                                        echo "<td>".$row2[0]."</td>";
				        echo "<td>".$row2[1]."</td>";
                                        echo "<td>".$row2[2]."</td>";
                                        echo "<td>".$row2[3]."</td>";
                                        echo "<td>".$row2[4]."</td>";
                                        echo "<td>".$row2[5]."</td>";
					echo "<td>".$row2[6]."</td>";
                                        echo "<td>".$row2[7]."</td>";
                                        echo "<td>".$row2[8]."</td>";

                                        echo "</tr>";
                                    }

                                     echo "</table>";

                                }

		               if(($result2)) {
                               //We are done with the result set returned above, so free it
                                    $result2->free_result();
                               }
                                // close down prepared statement
                                $stmt2->close();

                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }

		     } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }

	}
      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

<html>
<body>
     <style>
        body {font-family: 'verdana'; font-size: 18px;}
     </style>

</body>
</html>
