<head><title>Query 6</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';


	//Override the PHP configuration file to display all errors
	//This is useful during development but generally disabled before release
	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);


		   echo "<h2>In descending order of education spending per pupil, see each states highschool graduation rate and percent of adults who have completed at least some part of college </h2>";

		   //prepare statement and call query
			if ($stmt1 = $conn->prepare("CALL Query10()")) {

      			   //Run the actual query
      			   if ($stmt1->execute()) {

         		      //Store result set generated by the prepared statement
         		      $result1 = $stmt1->get_result();

         		      if (($result1) && ($result1->num_rows != 0)) {

            		      //Create table to display results
           		       echo "<table border=\"1px solid black\">";
            		       echo "<tr><th> State Name </th> <th> Education Spending Per Pupil </th><th> Highschool Graduation Rate</th> <th> Percent Completing College </th></tr>";

            		       //Report result set by visiting each row in it
            		       while ($row1 = $result1->fetch_row()) {
               		       	     echo "<tr>";
               			     echo "<td>".$row1[0]."</td>";
               			     echo "<td>".$row1[1]."</td>";
				     echo "<td>".$row1[2]."</td>";
				     echo "<td>".$row1[3]."</td>";
               			     echo "</tr>";
            			     }

            			     echo "</table>";

         			} else {

				  if(!($result1)) {
				  	echo "Internal error: procedure failed";
				  }
				}
				  
                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }
				
			   	// close down prepared statement
      			      	$stmt1->close();
			} else {
		           //Call to execute failed, e.g. because server is no longer reachable,
         	      	   //or because supplied values are of the wrong type
         	      	   echo "Execute failed.<br>";
			}
		} else {
       		  //A problem occurred when preparing the statement; check for syntax errors
       		  //and misspelled attribute names in the statement string.
      		  echo "Prepare failed.<br>";
      		  $error = $conn->errno . ' ' . $conn->error;
      		  echo $error;
             	}
		
 		 if ($stmt4 = $conn->prepare("CALL Query7()")) {

                           //Run the actual query
                           if ($stmt4->execute()) {

                              //Store result set generated by the prepared statement
                              $result4 = $stmt4->get_result();

                              if (($result4) && ($result4->num_rows != 0)) {

                              echo "<h3> Does teacher salary play a role in this? For states with the highest highschool graduation rate and average SAT/ACT scores, here are the average teacher starting salaries</h3>";

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> State </th> <th> Average Teacher Starting Salary</th></tr>";
                               //Report result set by visiting each row in it
                               while ($row4 = $result4->fetch_row()) {
			      
                                     echo "<tr>"; 
                                     echo "<td>".$row4[1]."</td>"; 
                                     echo "<td>".$row4[0]."</td>"; 
                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {

                                  if(!($result4)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }
                                  if(($result4)) {
                                        //We are done with the result set returned above, so free it
                                        $result4->free_result();
                                  }

                                // close down prepared statement
                                $stmt4->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                }
		
		
      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

