<head><title>Query 6</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';


	//Override the PHP configuration file to display all errors
	//This is useful during development but generally disabled before release
	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);

	//get user input and perform error-checking on it
	$q6state = $_POST['q6state'];


	if(!empty($q6state)) {
		$q6state = trim($q6state);
		if (strcmp($q6state, 'Alabama') == 0 || strcmp($q6state, 'Alaska') == 0 || strcmp($q6state, 'Arizona') == 0 || strcmp($q6state, 'Arkansas') == 0 || strcmp($q6state, 'California') == 0 || strcmp($q6state, 'Colorado') == 0 || strcmp($q6state, 'Connecticut') == 0 || strcmp($q6state, 'Delaware') == 0 || strcmp($q6state, 'Flordia') == 0 || strcmp($q6state, 'Georgia') == 0 || strcmp($q6state, 'Hawaii') == 0 || strcmp($q6state, 'Idaho') == 0 || strcmp($q6state, 'Illinois') == 0 || strcmp($q6state, 'Indiana') == 0 || strcmp($q6state, 'Iowa') == 0 || strcmp($q6state, 'Kansas') == 0 || strcmp($q6state, 'Kentucky') == 0 || strcmp($q6state, 'Louisiana') == 0 || strcmp($q6state, 'Maine') == 0 || strcmp($q6state, 'Maryland') == 0 || strcmp($q6state, 'Massachusetts') == 0 || strcmp($q6state, 'Michigan') == 0 || strcmp($q6state, 'Minnesota') == 0 || strcmp($q6state, 'Mississippi') == 0 || strcmp($q6state, 'Missouri') == 0 || strcmp($q6state, 'Montana') == 0 || strcmp($q6state, 'Nebraska') == 0 || strcmp($q6state, 'Nevada') == 0 || strcmp($q6state, 'New Hampshire') == 0 || strcmp($q6state, 'New Jersey') == 0 || strcmp($q6state, 'New Mexico') == 0 || strcmp($q6state, 'New York') == 0 || strcmp($q6state, 'North Carolina') == 0 || strcmp($q6state, 'North Dakota') == 0 || strcmp($q6state, 'Ohio') == 0 || strcmp($q6state, 'Oklahoma') == 0 || strcmp($q6state, 'Oregon') == 0 || strcmp($q6state, 'Pennsylvania') == 0 || strcmp($q6state, 'Rhode Island') == 0 || strcmp($q6state, 'South Carolina') == 0 || strcmp($q6state, 'South Dakota') == 0 || strcmp($q6state, 'Tennessee') == 0 || strcmp($q6state, 'Texas') == 0 || strcmp($q6state, 'Utah') == 0 || strcmp($q6state, 'Vermont') == 0 || strcmp($q6state, 'Virginia') == 0 || strcmp($q6state, 'Washington') == 0 || strcmp($q6state, 'West Virginia') == 0 || strcmp($q6state, 'Wisconsin') == 0 || strcmp($q6state, 'Wyoming') == 0 || strcmp($q6state, 'Washington DC') == 0 || strcmp($q6state, 'Puerto Rico') == 0) {
		
   		   //input is within range, so we can make stored procedure calls safely
		   echo "<h2>What is the difference between the US born and foreign born median incomes for $q6state , and how racially diverse is this state? How does this compare to states with the minimum and maximum median incomes?</h2><br>";

		   //call stored procedures defined on dbase

		   //values for states above and below threshold
		
			if ($stmt1 = $conn->prepare("CALL Query6(?)")) {
      			   $stmt1->bind_param("s", $q6state);

      			   //Run the actual query
      			   if ($stmt1->execute()) {

         		      //Store result set generated by the prepared statement
         		      $result1 = $stmt1->get_result();

         		      if (($result1) && ($result1->num_rows != 0)) {

            		      //Create table to display results
           		       echo "<table border=\"1px solid black\">";
            		       echo "<tr><th> ForeingBornIncome </th> <th> USBornIncome </th><th> white </th><th> black </th><th> asian </th><th> indigenous </th><th> other </th><th> hispanicOrLatino </th> <th> nonHispanicOrLatino </th></tr>";

            		       //Report result set by visiting each row in it
            		       while ($row1 = $result1->fetch_row()) {
               		       	     echo "<tr>";
               			     echo "<td>".$row1[0]."</td>";
               			     echo "<td>".$row1[1]."</td>";
				     echo "<td>".$row1[2]."</td>";
				     echo "<td>".$row1[3]."</td>";
				     echo "<td>".$row1[4]."</td>";
				     echo "<td>".$row1[5]."</td>";
				     echo "<td>".$row1[6]."</td>";
				     echo "<td>".$row1[7]."</td>";
				     echo "<td>".$row1[8]."</td>";
               			     echo "</tr>";
            			     }

            			     echo "</table>";

         			} else {

				  if(!($result1)) {
				  	echo "Internal error: procedure failed";
				  }
				}
				  
                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }
				
			   	// close down prepared statement
      			      	$stmt1->close();
			} else {
		           //Call to execute failed, e.g. because server is no longer reachable,
         	      	   //or because supplied values are of the wrong type
         	      	   echo "Execute failed.<br>";
			}
		} else {
       		  //A problem occurred when preparing the statement; check for syntax errors
       		  //and misspelled attribute names in the statement string.
      		  echo "Prepare failed.<br>";
      		  $error = $conn->errno . ' ' . $conn->error;
      		  echo $error;
             	}
	   } else {
	   
	     echo "We do not have information available for this state. Remember that the input must be a valid, capitalized state name";
	   }
	} else {
	  echo "State Name Not Set";
	}
      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

