<head><title>Query 2</title></head>
<body>
<?php
	//open a connection to dbase server
        include 'open.php';


	//Override the PHP configuration file to display all errors
	//This is useful during development but generally disabled before release
	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);

	//get user input and perform error-checking on it
	$teenPregRate = $_POST['teenPregRate'];


	if(!empty($teenPregRate)) {

		if (is_numeric($teenPregRate) && $teenPregRate >= 0 && $teenPregRate <= 100) {
		
   		   //input is within range, so we can make stored procedure calls safely
		   echo "<h2>What is the average household income for states where the teen pregnancy rate is above $teenPregRate %?</h2><br>";

		   //call stored procedures defined on dbase

		   //values for states above and below threshold
		
			if ($stmt1 = $conn->prepare("CALL Query2HigherUserInput(?)")) {
      			   $stmt1->bind_param("d", $teenPregRate);

      			   //Run the actual query
      			   if ($stmt1->execute()) {

         		      //Store result set generated by the prepared statement
         		      $result1 = $stmt1->get_result();

         		      if (($result1) && ($result1->num_rows != 0)) {

            		      //Create table to display results
           		       echo "<table border=\"1px solid black\">";
            		       echo "<tr><th> State </th> <th> Median Income </th></tr>";

            		       //Report result set by visiting each row in it
            		       while ($row1 = $result1->fetch_row()) {
               		       	     echo "<tr>";
               			     echo "<td>".$row1[0]."</td>";
               			     echo "<td>".$row1[1]."</td>";
               			     echo "</tr>";
            			     }

            			     echo "</table>";

         			} else {
        			  if ($result1->num_rows == 0) {
				     	echo "No states have a teen pregnancy rate above this threshold";
						     
				  }

				  if(!($result1)) {
				  	echo "Internal error: procedure failed";
				  }
				}
				  
                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }
				
			   	// close down prepared statement
      			      	$stmt1->close();
			} else {
		           //Call to execute failed, e.g. because server is no longer reachable,
         	      	   //or because supplied values are of the wrong type
         	      	   echo "Execute failed.<br>";
			}
		} else {
       		  //A problem occurred when preparing the statement; check for syntax errors
       		  //and misspelled attribute names in the statement string.
      		  echo "Prepare failed.<br>";
      		  $error = $conn->errno . ' ' . $conn->error;
      		  echo $error;
                }

		//get states with teen pregnancy rate below this threshold
		 if ($stmt2 = $conn->prepare("CALL Query2LowerUserInput(?)")) {
                           $stmt2->bind_param("d", $teenPregRate);

                           //Run the actual query
                           if ($stmt2->execute()) {

                              //Store result set generated by the prepared statement
                              $result2 = $stmt2->get_result();

                              if (($result2) && ($result2->num_rows != 0)) {

                              //Create table to display results
                               echo "<table border=\"1px solid black\">";
                               echo "<tr><th> State </th> <th> Median Income </th></tr>";

                               //Report result set by visiting each row in it
                               while ($row2 = $result2->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row2[0]."</td>";
                                     echo "<td>".$row2[1]."</td>";
                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {
                                  if ($result2->num_rows == 0) {
                                        echo "No states have a teen pregnancy rate below this threshold";

                                  }

                                  if(!($result2)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result2)) {
                                        //We are done with the result set returned above, so free it
					 $result2->free_result();
				  }

                                // close down prepared statement
                                $stmt2->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
		}	
	   } else {
	   
	     echo "Input must be a decimal between 0 and 100, inclusive";
	   }
	} else {
	  echo "Threshhold Not Set";
	}
      
   // close the connection opened by open.php
   $conn->close();

?>
</body>

