<!-- Sydney Friedel and Shelby Coe -->
<!-- sfriede5 and scoe4 -->

<head><title>Query 12</title></head>
 <body>
<?php     
    //open a connection to dbase server 
	include 'open.php';


	$stddev = $_POST['stddev12'];
//	echo $stddev; 
	if ($stddev >= 0 && $stddev <= 99999999.99) {

	// echo some basic header info onto the page
	echo "<h2>For states with an unemployment rate $stddev standard deviations above the national average, list the health and risk factor statistics.</h2>";

	                //prepare statements and call queries
                        if ($stmt1 = $conn->prepare("CALL Query12UI(?)")) {
			   $stmt1->bind_param("d", $stddev);
                           //Run the actual query
                           if ($stmt1->execute()) {

                              //Store result set generated by the prepared statement
                              $result1 = $stmt1->get_result();

                              if (($result1) && ($result1->num_rows != 0)) {
                     
                              //Create table to display results
                              echo "<table border=\"1px solid black\">";
 
                              echo "<tr><th> State </th><th>Unemployment Rate </th> <th> Abortion Rate </th><th> Homicide Rate </th><th> Number of Drug Overdoses</th><th> Suicide Rate</th><th>Teen Pregnancy Rate</th><th> Cancer Mortality Rate</th><th>STIs Per 100K</th><th>Obesity Prevalence</th></tr>";

                               //Report result set by visiting each row in it
                               while ($row1 = $result1->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row1[0]."</td>";
                                     echo "<td>".$row1[1]."</td>";
                                     echo "<td>".$row1[2]."</td>";
                                     echo "<td>".$row1[3]."</td>";
				     echo "<td>".$row1[4]."</td>";
                                     echo "<td>".$row1[5]."</td>";
                                     echo "<td>".$row1[6]."</td>";
                                     echo "<td>".$row1[7]."</td>";
                                     echo "<td>".$row1[8]."</td>";
                                     echo "<td>".$row1[9]."</td>";
                                     
                                     echo "</tr>";
                                     }

				     echo "</table>";

                                } else {

				  if($result1->num_rows == 0) {

				  	echo "No states have an unemployment rate this far from the national average";
				  }

                                  if(!($result1)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result1)) {
                                        //We are done with the result set returned above, so free it
                                        $result1->free_result();
                                  }

                                // close down prepared statement
                                $stmt1->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                 }




		 echo "<h2> How do the statistics for these states compare to the national averages? Here are the average statistics </h2>";

		          //prepare statements and call queries
                        if ($stmt = $conn->prepare("CALL Query12Avg()")) {
                           
                           //Run the actual query
                           if ($stmt->execute()) {

                              //Store result set generated by the prepared statement
                              $result = $stmt->get_result();

                              if (($result) && ($result->num_rows != 0)) {

                              //Create table to display results
                              echo "<table border=\"1px solid black\">";

                              echo "<tr><th>Unemployment Rate </th> <th> Abortion Rate </th><th> Homicide Rate </th><th> Number of Drug Overdoses</th><th> Suicide Rate</th><th>Teen Pregnancy Rate</th><th> Cancer Mortality Rate</th><th>STIs Per 100K</th><th>Obesity Prevalence</th></tr>";

                               //Report result set by visiting each row in it
                               while ($row1 = $result->fetch_row()) {
                                     echo "<tr>";
                                     echo "<td>".$row1[0]."</td>";
                                     echo "<td>".$row1[1]."</td>";
                                     echo "<td>".$row1[2]."</td>";
                                     echo "<td>".$row1[3]."</td>";
                                     echo "<td>".$row1[4]."</td>";
                                     echo "<td>".$row1[5]."</td>";
                                     echo "<td>".$row1[6]."</td>";
                                     echo "<td>".$row1[7]."</td>";
                                     echo "<td>".$row1[8]."</td>";
                                     echo "<td>".$row1[9]."</td>";
		     
                                     echo "</tr>";
                                     }

                                     echo "</table>";

                                } else {

                                  if(!($result)) {
                                        echo "Internal error: procedure failed";
                                  }
                                }

                                  if(($result)) {
                                        //We are done with the result set returned above, so free it
                                        $result->free_result();
                                  }

                                // close down prepared statement
                                $stmt->close();
                        } else {
                           //Call to execute failed, e.g. because server is no longer reachable,
                           //or because supplied values are of the wrong type
                           echo "Execute failed.<br>";
                        }
                } else {
                  //A problem occurred when preparing the statement; check for syntax errors
                  //and misspelled attribute names in the statement string.
                  echo "Prepare failed.<br>";
                  $error = $conn->errno . ' ' . $conn->error;
                  echo $error;
                 }


	  } else {

	    echo "Please enter a nonnegative number between 0 and 99999999.99";
	  }
	  
   // close the connection opened by open.php
   $conn->close();

?>
</body>
<html>
<body>
     <style>
        body {font-family: 'verdana'; font-size: 18px;}
     </style>

</body>
</html>
